name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/London

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_colors: github
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 15

          # Hide some noisy languages, but keep Shell
          plugin_languages_ignored: >
            Jupyter Notebook, HTML, PHP, Makefile, CSS, C#, Hack, JSON, Markdown, Unity3D Asset, Javascript, Pip Requirements, YAML, TOML

          # Don’t group everything into “Other”
          plugin_languages_other: no
